"""``agentseek deploy`` — generate deployment manifests for the project.

v1 only supports ``--dry-run``: render docker-compose / k8s YAML files into
the chosen output directory. The actual cluster/registry interactions land
in a follow-up PR; the flag surface here is stable.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Annotated

import jinja2
import typer

# ---------------------------------------------------------------------------
# Templates (Jinja2). Inline so the package stays single-file deployable.
# ---------------------------------------------------------------------------

_COMPOSE_TEMPLATE = """\
# Generated by `agentseek deploy --dry-run`.
# Edit, commit, then run `docker compose up -d` from this directory.
services:
  {{ slug }}:
    image: {{ image }}
    env_file:
      - .env
    ports:
      - "{{ port }}:{{ port }}"
    restart: unless-stopped
"""

_K8S_DEPLOYMENT_TEMPLATE = """\
# Generated by `agentseek deploy --dry-run`.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ slug }}
  namespace: {{ namespace }}
  labels:
    app: {{ slug }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ slug }}
  template:
    metadata:
      labels:
        app: {{ slug }}
    spec:
      containers:
        - name: {{ slug }}
          image: {{ image }}
          ports:
            - containerPort: {{ port }}
          envFrom:
            - configMapRef:
                name: {{ slug }}-env
                optional: true
"""

_K8S_SERVICE_TEMPLATE = """\
# Generated by `agentseek deploy --dry-run`.
apiVersion: v1
kind: Service
metadata:
  name: {{ slug }}
  namespace: {{ namespace }}
  labels:
    app: {{ slug }}
spec:
  type: ClusterIP
  selector:
    app: {{ slug }}
  ports:
    - port: {{ port }}
      targetPort: {{ port }}
      protocol: TCP
"""


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------


class DeployMode(StrEnum):
    DOCKER_COMPOSE = "docker-compose"
    K8S = "k8s"
    BOTH = "both"


@dataclass(frozen=True)
class DeployContext:
    """Render-time inputs for the deploy templates."""

    slug: str
    image: str
    port: int
    replicas: int
    namespace: str

    def as_dict(self) -> dict[str, object]:
        return {
            "slug": self.slug,
            "image": self.image,
            "port": self.port,
            "replicas": self.replicas,
            "namespace": self.namespace,
        }


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------


def _render(template_source: str, ctx: DeployContext) -> str:
    # YAML is plain text; HTML autoescaping would corrupt the manifest.
    template = jinja2.Template(template_source, autoescape=False, keep_trailing_newline=True)
    return template.render(**ctx.as_dict())


def _render_compose(ctx: DeployContext) -> str:
    return _render(_COMPOSE_TEMPLATE, ctx)


def _render_k8s_deployment(ctx: DeployContext) -> str:
    return _render(_K8S_DEPLOYMENT_TEMPLATE, ctx)


def _render_k8s_service(ctx: DeployContext) -> str:
    return _render(_K8S_SERVICE_TEMPLATE, ctx)


# ---------------------------------------------------------------------------
# Slug / context resolution
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """Mirror ``build``'s slug heuristic so generated tags & manifests align."""
    cleaned = "".join(ch.lower() if (ch.isalnum() or ch in {"-", "_"}) else "-" for ch in name)
    cleaned = cleaned.replace("_", "-").replace(" ", "-")
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-") or "app"


def _resolve_slug(cwd: Path, override: str | None) -> str:
    if override:
        return _slugify(override)
    return _slugify(cwd.name)


def _resolve_image(slug: str, override: str | None) -> str:
    return override or f"{slug}:latest"


# ---------------------------------------------------------------------------
# File output
# ---------------------------------------------------------------------------


def _plan_files(mode: DeployMode, ctx: DeployContext, output: Path) -> dict[Path, str]:
    """Return ``{path: rendered}`` map for the requested mode."""
    files: dict[Path, str] = {}
    if mode in (DeployMode.DOCKER_COMPOSE, DeployMode.BOTH):
        files[output / "docker-compose.yaml"] = _render_compose(ctx)
    if mode in (DeployMode.K8S, DeployMode.BOTH):
        files[output / "k8s" / "deployment.yaml"] = _render_k8s_deployment(ctx)
        files[output / "k8s" / "service.yaml"] = _render_k8s_service(ctx)
    return files


def _write_files(files: dict[Path, str]) -> None:
    overwrites = [path for path in files if path.exists()]
    if overwrites:
        typer.echo("Overwriting existing manifest files:")
        for path in overwrites:
            typer.echo(f"  - {path}")
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        typer.echo(f"wrote {path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

app = typer.Typer(
    name="deploy",
    help="Generate deployment manifests (docker-compose / k8s).",
    add_completion=False,
    no_args_is_help=False,
)


@app.callback(invoke_without_command=True)
def deploy(
    dry_run: Annotated[
        bool,
        typer.Option(
            "--dry-run",
            help="Generate manifest files without performing an actual deployment. Required in v1.",
        ),
    ] = False,
    mode: Annotated[
        DeployMode,
        typer.Option(
            "--mode",
            case_sensitive=False,
            help="Deployment target: docker-compose | k8s | both.",
        ),
    ] = DeployMode.BOTH,
    output: Annotated[
        Path,
        typer.Option(
            "--output",
            help="Directory to write manifests into.",
            file_okay=False,
            dir_okay=True,
            resolve_path=False,
        ),
    ] = Path("./deploy"),
    image: Annotated[
        str | None,
        typer.Option(
            "--image",
            help="Container image reference. Default: <project-slug>:latest.",
            show_default=False,
        ),
    ] = None,
    slug: Annotated[
        str | None,
        typer.Option(
            "--slug",
            help="Project slug used in service / deployment names. Default: inferred from cwd name.",
            show_default=False,
        ),
    ] = None,
    port: Annotated[
        int,
        typer.Option("--port", help="Service port exposed by the workload."),
    ] = 8000,
    replicas: Annotated[
        int,
        typer.Option("--replicas", help="Replicas for the k8s Deployment.", min=1),
    ] = 1,
    namespace: Annotated[
        str,
        typer.Option("--namespace", help="Namespace for the k8s manifests."),
    ] = "default",
) -> None:
    if not dry_run:
        typer.echo(
            "Only --dry-run is supported in v1. Re-run with --dry-run to generate manifests.",
            err=True,
        )
        raise typer.Exit(2)

    cwd = Path.cwd()
    resolved_slug = _resolve_slug(cwd, slug)
    resolved_image = _resolve_image(resolved_slug, image)
    ctx = DeployContext(
        slug=resolved_slug,
        image=resolved_image,
        port=port,
        replicas=replicas,
        namespace=namespace,
    )

    files = _plan_files(mode, ctx, output)
    _write_files(files)

    typer.echo(
        f"agentseek deploy --dry-run --mode {mode.value} → "
        f"{len(files)} file(s) under {output} (image={resolved_image}, slug={resolved_slug})."
    )


__all__ = [
    "DeployContext",
    "DeployMode",
    "app",
]
